name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Restore pub cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Pub get
        run: flutter pub get

      # 1) Проверка форматирования
      - name: Check format
        run: dart format --output=none --set-exit-if-changed .

      # 2) Анализ кода
      - name: Analyze
        run: flutter analyze

      # 3) Тесты + coverage
      - name: Test
        run: flutter test --coverage

      # 4) (опц.) собрать example/, если это пакет с примером
      - name: Build example (optional)
        if: hashFiles('example/pubspec.yaml') != ''
        working-directory: example
        run: |
          flutter pub get
          flutter build apk --debug
